name: shell commands
on: [push,pull_request]
jobs:
  run-shell-command: 
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello first program"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python shell
        run: |
          import os  
          print(os.environ['PATH'])
        shell: python
  
  run-python-command:
    runs-on: ubuntu-latest
    needs: ["run-shell-command"]
    steps:
      - name: python depends on
        run: |
          import platform
          print(platform.processor())
        shell: python
        